### ISSUE TITLE
Fails to install on Windows

### ISSUE THREAD

**Issue by super-tomcat** [sogaiu/janet-emacs-trial-kit#1] opened 2024-05-13 11:14 UTC
Emacs 29.2 - Windows 11 Pro

Multiple errors during install about missing this and that and then when you try janet jetk again you get:

File is missing: Cannot open load file, No such file or directory, elpaca

**Comment by sogaiu** [comment] 2024-05-13 12:21
Thanks for the report.

Since switching to using elpaca I hadn't tried on Windows.  I'll look into it.

FWIW, commits from [here](https://github.com/sogaiu/janet-emacs-trial-kit/commit/51f9b1db9d414d7cd0b832ca40785c9c948149cc) or earlier might work as those are from pre-elpaca days.

**Comment by sogaiu** [comment] 2024-05-13 13:14
I confirmed that things don't work on Windows ATM, sorry about that.

I tested some earlier commits and found the following two to function better in my Windows 10 environment (assuming the various symlink-related settings described in the README have been made):

* 86b8bb84d0cf9b1b3031b93649759aca13b7a109 - didn't see any errors and the few things I tried seemed to work
* 51f9b1db9d414d7cd0b832ca40785c9c948149cc - saw some errors, but basic interaction with janet via ajrepl worked

Intend to investigate further, but perhaps the former of the two commits can be considered a work-around for now.

**Comment by super-tomcat** [comment] 2024-05-13 13:27
Okay thanks, yes i tried your first suggestion and replaced the init.el file... this seemed to work okay at installing the needed packages but kept hanging on flycheck saying this: error: Empty checkout for flycheckerror: Empty checkout for flycheck

So i commented out all the flycheck stuff out in the init.el file and it then started up no problem, and the REPL worked with sample.janet etc

Although it was a pain for me to suddenly end up with a very basic Emacs! 🤣

What i will do is incorporate the needed packages one at a time into my current version of Emacs and go from there, to be honest i am not really bothered about Flycheck (and the other Fly checker who's name escapes me) as they always seem to end up having to be switched off anyway.

Emacs is my main text editor so it would be good to try Janet out in that rather than some other text editor.

Thanks again for all the help 👍

**Comment by sogaiu** [comment] 2024-05-13 14:42
Sorry for the bumpy experience.  Thanks for opening this issue and sharing what worked for you.

Hopefully I can fix things up for future users.

**Comment by sogaiu** [comment] 2024-05-14 00:26
It looks like avoiding the use of symlinks makes things work on Windows [1].

I've made [this change](https://github.com/sogaiu/janet-emacs-trial-kit/commit/5b88e36c6b3bf83b2c0188f3319dd11d47d4fb9e) so that symlinks are not used for any system.

This seems to work on Void Linux as well so I'm inclined to give this approach a try for a while.

I've also updated the documentation related to Windows here and there.

Going to close this for now, but if things are not working, please feel free to re-open / comment.

---

[1] Occasionally, an error occurs with elpaca itself on startup, but I haven't figured out why.  A work-around appears to be to just try again (i.e. invoke `janet jetk` after quitting emacs).  Mysterious...

**Closed as completed by sogaiu** 2024-05-14 00:26 UTC
